[build]
# Serve static files from the public directory
publish = "public"
# Remove Python files before Netlify tries to install dependencies
command = "bash ./ignore-python.sh"

# Only serve static files
ignore = "git diff --quiet $COMMIT_REF $COMMIT_REF^ --exit-code -- public; test $? -eq 1"

# Redirect SPA requests to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
